# Generated by Django 5.0.3 on 2024-03-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmember',
            name='address',
            field=models.ManyToManyField(blank=True, related_name='member_addresses', to='school.address'),
        ),
        migrations.AddField(
            model_name='schoolmember',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='school.occupation'),
        ),
        migrations.AddField(
            model_name='schoolmember',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='student_parents', to='school.parent'),
        ),
        migrations.AddField(
            model_name='schoolmember',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='school.program'),
        ),
        migrations.AddField(
            model_name='schoolmember',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='school.center'),
        ),
        migrations.AddField(
            model_name='schoolmember',
            name='sibling',
            field=models.ManyToManyField(blank=True, related_name='student_siblings', to='school.sibling'),
        ),
        migrations.AddField(
            model_name='user',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.schoolmember'),
        ),
    ]
